export const SELECTORS = {
  accordion: ".animated-accordion",
  accordionToggle: ".animated-accordion-toggle",
  accordionContent: ".animated-accordion-content",
  iconPlus: ".icon-plus",
  iconMinus: ".icon-minus",
  menuBtn: "#menu-btn",
  mobileMenu: "#mobile-menu",
  closeMenu: "#close-menu",
  cartBtn: "#cart-animated-btn",
  cartText: "#cart-btn-text",
  cartIcon: "#cart-btn-cart",
  checkIcon: "#cart-btn-check",
  count: "#count",
  decrease: "#decrease",
  increase: "#increase",
  cartIconNav: 'a[aria-label="Cart"]',
  cartBadge: "#cart-badge",
  radioBuyOnce: 'input[name="choice"][value="option1"]',
  radioSubscribe: 'input[name="choice"][value="option2"]',
  searchBtnDesktop: "#search-btn-desktop",
  searchBtnMobile: "#search-btn-mobile",
  searchModal: "#search-modal",
  closeSearchModal: "#close-search-modal",
  searchInput: "#search-input",
};
